//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnPTestResultsNotificationJob
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileTrackingBaselineSet
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Build { get; set; }
        public string FileHash { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public byte[] FileContents { get; set; }
    }
}
