//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnPTestResultsNotificationJob
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResultSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestResultSet()
        {
            this.TestResultMessageSets = new HashSet<TestResultMessageSet>();
        }
    
        public int Id { get; set; }
        public string TestCaseName { get; set; }
        public int Outcome { get; set; }
        public System.TimeSpan Duration { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorStackTrace { get; set; }
        public System.DateTimeOffset StartTime { get; set; }
        public System.DateTimeOffset EndTime { get; set; }
        public string ComputerName { get; set; }
        public int TestRunId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestResultMessageSet> TestResultMessageSets { get; set; }
        public virtual TestRunSet TestRunSet { get; set; }
    }
}
