//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnPTestResultsNotificationJob
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersSet
    {
        public int Id { get; set; }
        public string UPN { get; set; }
        public string Name { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsCoreMember { get; set; }
        public bool SendTestResults { get; set; }
        public string Email { get; set; }
        public bool IsEmailVerified { get; set; }
    }
}
