//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchQueryTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SearchQueryTool.HelpPageResources", typeof(HelpPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -ContentClass=urn:content-class:SPSPeople.
        /// </summary>
        internal static string hiddenconstraints_ex {
            get {
                return ResourceManager.GetString("hiddenconstraints_ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9399df62-f089-4033-bdc5-a7ea22936e8e.
        /// </summary>
        internal static string rankingmodelid_ex {
            get {
                return ResourceManager.GetString("rankingmodelid_ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filetype:equals(&quot;pptx&quot;).
        /// </summary>
        internal static string refinementfilters_ex {
            get {
                return ResourceManager.GetString("refinementfilters_ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to companies,contentclass,ContentType(filter=7/0/*),FileExtension(filter=7/0/*),FileType(filter=6/0/*).
        /// </summary>
        internal static string refiners_ex {
            get {
                return ResourceManager.GetString("refiners_ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path,Url,Title,Author,Write,ServerRedirectedEmbedURL,WorkId.
        /// </summary>
        internal static string selectproperties_ex {
            get {
                return ResourceManager.GetString("selectproperties_ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank:descending,modifiedby:ascending.
        /// </summary>
        internal static string sortlist_ex {
            get {
                return ResourceManager.GetString("sortlist_ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPSite|My Site Collection Source.
        /// </summary>
        internal static string sourceid_ex {
            get {
                return ResourceManager.GetString("sourceid_ex", resourceCulture);
            }
        }
    }
}
