//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnPAutomationUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileTrackingSet
    {
        public int Id { get; set; }
        public System.DateTime TestDate { get; set; }
        public string Build { get; set; }
        public string FileName { get; set; }
        public string FileHash { get; set; }
        public bool FileChanged { get; set; }
        public string TestSiteUrl { get; set; }
        public string TestUser { get; set; }
        public string TestAppId { get; set; }
        public string TestComputerName { get; set; }
    }
}
