//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnPAutomationUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestRunSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestRunSet()
        {
            this.TestResultSets = new HashSet<TestResultSet>();
        }
    
        public int Id { get; set; }
        public int TestConfigurationId { get; set; }
        public System.DateTime TestDate { get; set; }
        public Nullable<System.TimeSpan> TestTime { get; set; }
        public string Build { get; set; }
        public int Status { get; set; }
        public bool TestWasAborted { get; set; }
        public bool TestWasCancelled { get; set; }
        public Nullable<int> TestsPassed { get; set; }
        public Nullable<int> TestsSkipped { get; set; }
        public Nullable<int> TestsFailed { get; set; }
        public Nullable<int> TestsNotFound { get; set; }
        public string MSBuildLog { get; set; }
    
        public virtual TestConfigurationSet TestConfigurationSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestResultSet> TestResultSets { get; set; }
    }
}
