//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnPAutomationUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestConfigurationSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestConfigurationSet()
        {
            this.TestConfigurationPropertySets = new HashSet<TestConfigurationPropertySet>();
            this.TestRunSets = new HashSet<TestRunSet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string VSBuildConfiguration { get; set; }
        public string Branch { get; set; }
        public int Type { get; set; }
        public string TenantUrl { get; set; }
        public string TestSiteUrl { get; set; }
        public int TestAuthentication_Id { get; set; }
        public bool AnonymousAccess { get; set; }
    
        public virtual TestAuthenticationSet TestAuthenticationSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestConfigurationPropertySet> TestConfigurationPropertySets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestRunSet> TestRunSets { get; set; }
    }
}
